#!/bin/bash
## Requirements pv tool
## sudo apt install pv
## Create test file and upload it to your cloud destination
## fallocate -l 100M testfile

## More scripts at: https://github.com/ajkis/scripts
## If you find script useful feel free to buy me a beer at https://paypal.me/ajki
if pidof -o %PPID -x "copyspeedtest"; then
   echo "Already running, exiting."
   exit 1
fi

SOURCE="/mnt/unionfs/testfile" # SET PATH TO FILE
DESTINATION="/tmp/copytestfile"

if [[ -f "$DESTINATION" ]]; then
    rm "$DESTINATION"
fi
start=$(date +'%s')
echo "COPY SPEED TEST START"
echo "|   PROGRESSs   |   RATE   | AVG. RATE |"
pv --bytes --progress --rate --average-rate --timer --eta "$SOURCE" > "$DESTINATION"
echo "Finished in $(($(date +'%s') - $start)) seconds"
rm "$DESTINATION"
exit
