#!/bin/bash
# Requirements pv tool
# sudo apt install pv
if pidof -o %PPID -x "copyspeedtest"; then
   echo "Already running, exiting."
   exit 1
fi

SOURCE="/mnt/unionfs/testfile"
DESTINATION="/tmp/copytestfile"

if [[ -f "$DESTINATION" ]]; then
    rm "$DESTINATION"
fi
start=$(date +'%s')
echo "COPY SPEED TEST START"
echo "|   PROGRESSs   |   RATE   | AVG. RATE |"
pv --bytes --progress --rate --average-rate --timer --eta "$SOURCE" > "$DESTINATION"
echo "Finished in $(($(date +'%s') - $start)) seconds"
rm "$DESTINATION"
exit
