#!/bin/bash
## THIS SCRIPT WILL GENERATE FOLDER LIST BEFORE UPLOADING.
## THE SECOND SCRIPT PLEXREFRESHFOLDERS WILL RUN PLEX SCANNER ONLY ON NEWLY UPLOADED FOLDERS.
## NOTE: THIS IS CANIBALISED FROM MY ORIGINAL SCRIPT SO CHECK ALL PATHS 
if pidof -o %PPID -x "$0"; then
   echo "$(date "+%d.%m.%Y %T") Already running, exiting."
   exit 1
fi
LOGFILE="/home/plex/logs/local2acdcrypt.cron.log"

readarray -t UPLOAD < <(find /storage/local/ -mindepth 1  -type d -mmin +15 -not -path '*/\.*' -not -iname '*.partial*' | sort -uz) 
if [[ -n $UPLOAD ]]; then
    start=$(date +'%s')
    echo "$(date "+%d.%m.%Y %T") START" | tee -a "$LOGFILE"

    TimeStamp=`date +%Y-%m-%d_%H-%M-%S`
    PATHREPLACE=/storage/local/
    REPLACEDPATH=/mnt/unionfs/
    PATHACD=/mnt/acdcrypt/

    for task in "${UPLOAD[@]}"
    do
        if [[  $task == *"/movies/"* ]] || [[ $task == *"/series/"* ]] && [[ $task != "/mnt/unionfs/movies" ]] && [[ $task != "/mnt/unionfs/series" ]] ; then
            FOLDER="${task/$PATHREPLACE/$REPLACEDPATH}" # Change path from /storage/local/ to /mnt/unionfs
            echo "Adding to plex.list: $FOLDER" | tee -a "$LOGFILE"        
            echo "$FOLDER" >>/home/plex/.cache/$TimeStamp-plex.list
        fi       
    done

    # RCLONE MOVE FILES ( CHANGE TO YOUR PATHS )
    /usr/bin/rclone move /storage/local/ acdcrypt: -v --no-traverse --transfers=20 --checkers=20 --delete-after --min-age 15m --stats 30s --filter-from=/home/plex/.config/rclone/upload-filter --log-file=$LOGFILE
    #UPLOAD PLEX.LIST
    if  [[ -f  /home/plex/.cache/$TimeStamp-plex.list ]]; then
         echo "Uploading: $TimeStamp-plex.list" | tee -a "$LOGFILE"
         /usr/bin/rclone move /home/plex/.cache/$TimeStamp-plex.list acdcrypt:/tmp/ -v --no-traverse --log-file=$LOGFILE
    fi
    echo "$(date "+%d.%m.%Y %T") ENDED in $(($(date +'%s') - $start)) seconds" | tee -a "$LOGFILE"
fi
exit
