#!/bin/bash
## THIS SCRIPT WILL RUN PLEX SCANNER ONLY ON FOLDERS PREVIOUSLY GENERATED BY plexgeneratefolderlist.sh

if pidof -o %PPID -x "$0"; then
   echo "$(date "+%d.%m.%Y %T") Exit, already running."
   exit 1
fi
TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
LOGFILE="/home/plex/logs/plexrefresh.cron.log"
UNIONFSPATH="/mnt/unionfs/"
RCLONEREMOTE="acdcrypt:"
GETLISTS="find $UNIONFSPATH -type f -iname *.list -mmin +1"
CACHE="/home/plex/.cache/"
TVSECTION=1
MOVIESECTION=2

export LD_LIBRARY_PATH=/usr/lib/plexmediaserver
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/var/lib/plexmediaserver/Library/Application\ Support

# MERGE ALL AVAILABLE LISTS
$GETLISTS -exec cat {} + >> $CACHE/$TIMESTAMP-plex.list
if [[ ! -s $CACHE/$TIMESTAMP-plex.list ]] ; then
    exit
fi
# REMOVE DUPLICATE FOLDERS
sort $CACHE/$TIMESTAMP-plex.list | uniq | tee $CACHE/$TIMESTAMP-plex.list > /dev/null

# DELETE AVAILABLE LISTS FROM RLONE REMOTE
readarray -t PLEXLISTS < <($GETLISTS)
for PLIST in "${PLEXLISTS[@]}"
do
    PLIST=$(basename "${PLIST}")
    /usr/bin/rclone delete $RCLONEREMOTE/tmp/$PLIST
done

# PLEX SCAN NEW FOLDERS
readarray -t FOLDERS < $CACHE/$TIMESTAMP-plex.list
for FOLDER in "${FOLDERS[@]}"
do
    if [[  $FOLDER == *"/movies/"* ]] ; then
        echo "$(date "+%d.%m.%Y %T") Refreshing movie folder: $FOLDER" | tee -a "$LOGFILE"
        $LD_LIBRARY_PATH/Plex\ Media\ Scanner --scan --refresh --section $MOVIESECTION --directory "${FOLDER}" | tee -a "$LOGFILE"
    fi
    if [[  $FOLDER == *"/series/"* ]] ; then
        echo "$(date "+%d.%m.%Y %T") Refreshing serie folder: $FOLDER" | tee -a "$LOGFILE"
        $LD_LIBRARY_PATH/usr/lib/plexmediaserver/Plex\ Media\ Scanner --scan --refresh --section $TVSECTION --directory "${FOLDER}" | tee -a "$LOGFILE"
    fi
done
# ADD SUFFIX DONE TO THE FINISHED LIST
echo "$TIMESTAMP-plex.list.done" | tee -a "$LOGFILE"
mv $CACHE/$TIMESTAMP-plex.list $CACHE/$TIMESTAMP-plex.list.done
exit
